### ISSUE TITLE
[Bug] The background on survey items doesn't display fullscreen

### ISSUE THREAD

**Issue by hoangnguyen92dn** [longdt57/nimble-android-assignment#23]
## Issue

The background on survey items doesn't match the design on Figma

| App | Design |
|-|-|
| <img src="https://user-images.githubusercontent.com/6950766/168767170-a993cedb-8d61-4716-b71d-f7d6d39d1d9d.png" width=300 /> | <img src="https://user-images.githubusercontent.com/6950766/168767534-31db0d72-b033-4e47-bfd5-9bd3ba855dc5.png" width=300 /> |

## Expected

The background display fullscreen

**Comment by longdt57** [comment]
Hi Huey.
I'll update the Image scale type to center crop to make fullscreen. Is it okay?

**Comment by hoangnguyen92dn** [comment]
> Hi Huey. I'll update the Image scale type to center crop to make fullscreen. Is it okay?

@longdt57 Yup...Work for me 👌 

Btw, your image attachment on the comment above cannot be loaded.

**Comment by longdt57** [comment]
Yup. Let me check it

**Comment by longdt57** [comment]
![image](https://user-images.githubusercontent.com/8809113/168949564-3a029913-e0ff-4b38-a5f0-87bfe1ae2690.png)

**Comment by longdt57** [comment]
![Screenshot_20220518_101319](https://user-images.githubusercontent.com/8809113/168949807-219abd29-f7c9-454f-b361-af35f2751224.png)
