### ISSUE TITLE
[Bug] The user avatar is changed after back from detail screen

### ISSUE THREAD

**Issue by hoangnguyen92dn** [longdt57/nimble-android-assignment#24]
## Issue

When navigating to the Detail screen and then back to Home, the user avatar in the top-right corner is changed.

https://user-images.githubusercontent.com/6950766/168769830-78bc8075-c8ad-4b72-a7ba-8ec20bc42a55.mp4

## Expected

Display user avatar correctly when navigating back.

**Comment by longdt57** [comment]
I fixed it in PR #37 

```
