### ISSUE TITLE
[Improvement] Mapping survey list to ui models issue 

### ISSUE THREAD

**Issue by hoangnguyen92dn** [longdt57/nimble-android-assignment#26]
### Issue

I am wondering about the chain of extension you are using when mapping the surveys to UI models on the block code below, would it be possible to get rid of `toSet().toList()`? 🤔  Don't hesitate to share your idea if it is required for a specific reason.

https://github.com/longdt57/nimble-android-assignment/blob/0249943d406b6975f9bf93cab1ef88686d4a0ca1/app/src/main/java/co/nimble/lee/assignment/ui/screens/home/HomeViewModel.kt#L87-L95

### Expected

Remove unnecessary extension calls on mapping for better performance.

**Comment by longdt57** [comment]
I'm afraid of duplicating for the below case:

Step 1. getSurveyRemote(page[number]=1, page[size] = 5)

```Response:
"data":...
"meta": {
    "page": 1,
    "pages": 10,
    "page_size": 2,
    "records": 20
  }
```
Step 2: getSurveyRemote(page[number]=1, page[size] = 10)
```
Response: Network Error
=> Return Local Database
```
For this case, the currently displayed survey list is duplicated with the local database.

**Comment by longdt57** [comment]
I fixed it by adding the flag **shouldLoadDatabaseIfFail** in MR #33 

```
HomeViewModel
...
            val param = GetSurveyUseCase.Param(pageInfo.first, pageInfo.second, shouldLoadDatabaseIfFail = false)
            when (val result = getSurveyUseCase.invoke(parameters = param)) {
                is UseCaseResult.Success -> {
                    _surveyUiModels.apply {
                        value = value.toMutableList().apply {
                            addAll(result.data.first.toSurveyUiModel())
                        }
                    }

GetSurveyUseCase
...
if (param.isFirstPage() && param.shouldLoadDatabaseIfFail) Pair(surveyRepository.getSurveysLocal(), null)
```

**Comment by hoangnguyen92dn** [comment]
> For this case, the currently displayed survey list is duplicated with the local database.

@longdt57 You mean by adding `.toSet().toList()` it will prevent the issue? 🤔

**Comment by longdt57** [comment]
Yeap. 
Step 1: current display survey list is the first 5 surveys on page 1.
Steps 2: Current display + database surveys (first 5 surveys page 1 cache before) => duplicate.

Anyway, I changed the UseCase not to return database surveys if at least 1 survey is displayed.

**Comment by hoangnguyen92dn** [comment]
@longdt57 Do you think it is related to object reference in memory somehow? 🤔

**Comment by longdt57** [comment]
In my opinion, that is the **UseCase** error.

The previous error UseCase could make duplicate surveys.
- The surveys is loaded from the database if both the network fails and: **load pageNumber = 1** (`getSurveys(), loadMoreSurveys() - case pageSize >= defaultSize 5`)
```
return try {
GetSurveyUseCase
           ...
            if (param.isFirstPage()) Pair(surveyRepository.getSurveysLocal(), null)
        
```

The new UseCase:
- Only load the surveys from the database if the network fails and: **load page 1** (`getSurveys`)
```
GetSurveyUseCase
...
if (param.isFirstPage() && param.shouldLoadDatabaseIfFail) Pair(surveyRepository.getSurveysLocal(), null)

**Comment by longdt57** [comment]
That's right. But that case never happens because I clear the database if page 1 loads successfully

**Comment by hoangnguyen92dn** [comment]
@longdt57 It looks like a workaround solution since it was still working when you apply `toSet().toList()` 🤷‍♂️

**Comment by hoangnguyen92dn** [comment]
I think you will need deeper insight into the `apply` block when adding the list to `value` reference. I am going to close the issue for now.

```
         _surveyUiModels.apply { 
             value = value.toMutableList().apply { 
                 addAll(result.data.first.toSurveyUiModel()) 
             }.toSet().toList() 
         } 
```

**Comment by longdt57** [comment]
Could you give me a sample of improving it. It might be better for me due to the mean-time
