### ISSUE TITLE
[Improvement] Inconsistency naming convention

### ISSUE THREAD

**Issue by hoangnguyen92dn** [longdt57/nimble-android-assignment#27]
### Issue

- There are 2 different suffix for `UiModel`: `SurveyUIModel` and `UserUiModel`. Would be it possible to update it for consistency.

https://github.com/longdt57/nimble-android-assignment/blob/0249943d406b6975f9bf93cab1ef88686d4a0ca1/app/src/main/java/co/nimble/lee/assignment/model/SurveyUIModel.kt#L8-L13

https://github.com/longdt57/nimble-android-assignment/blob/0249943d406b6975f9bf93cab1ef88686d4a0ca1/app/src/main/java/co/nimble/lee/assignment/model/UserUiModel.kt#L5-L11

- Following Kotlin style, we don't use snake case for package

![image](https://user-images.githubusercontent.com/6950766/168783168-bad7b49a-b3b7-480d-8ae1-51ad634594ad.png)

### Expected

Naming classes, models, and packages must follow the convention for consistency.

**Comment by longdt57** [comment]
Fixed in MR #35
SurveyUIModel -> SurveyUiModel
token_help -> tokenhelper
