### ISSUE TITLE
[Improvement] String extension returns URL High Resolution

### ISSUE THREAD

**Issue by hoangnguyen92dn** [longdt57/nimble-android-assignment#28]
### Issue

Just curious if this extension always returns URL high resolution on any string? I.e: `"nimble".getUrlHighResolution()` -> `nimblel` then it doesn't make sense in this case; furthermore, if I have another URL for the user avatar and it doesn't support by appending the `l` for the high-resolution image then using this extension could break the original URL. How do you think?

https://github.com/longdt57/nimble-android-assignment/blob/0249943d406b6975f9bf93cab1ef88686d4a0ca1/app/src/main/java/co/nimble/lee/assignment/ui/screens/ext/StringExt.kt#L3

https://github.com/longdt57/nimble-android-assignment/blob/0249943d406b6975f9bf93cab1ef88686d4a0ca1/app/src/main/java/co/nimble/lee/assignment/ui/screens/ext/ImageViewExt.kt#L7-L13

### Expected

Avoid confusion when using extension

**Comment by longdt57** [comment]
I agree with you. I update it in #36 
I moved it to a **UrlUtil** object for reuse.

**Comment by hoangnguyen92dn** [comment]
@longdt57 You might be confused about the idea, I meant that the extension returns URL for high resolution is only being used for Survey so making it `public` access extension doesn't make sense tho. Furthermore, changing the URL right before loading should be avoided, the input is the original URL then it loads another URL? 🤷‍♂️

**Comment by longdt57** [comment]
How about put `getUrlHighResolution()` to the SurveyUiModel class?
I used to think about it.

**Comment by longdt57** [comment]
It'll look like
```
data class SurveyUiModel(
    val id: String,
    val title: String?,
    val description: String?,
    private val coverImageUrl: String?
) : Parcelable {

    fun getUrlHighResolution(): String = coverImageUrl + "l"
}

ivCover.loadSurveyCoverImage(surveyUiModel.getUrlHighResolution())
```

**Comment by hoangnguyen92dn** [comment]
> How about put getUrlHighResolution() to the SurveyUiModel class?

👍 Yup looks good to me. Or we could create a new property for the URL high resolution, then when mapping we could assign the value for it.

```
data class SurveyUiModel(
    val id: String,
    val title: String?,
    val description: String?,
    val coverImageUrl: String?
    val coverImageHighResolutionUrl: String?
)
```

**Comment by longdt57** [comment]
If we never use the origin `coverImageUrl`, I suggest replacing it with `coverImageHighResolutionUrl` at all to reduce the duplicate variable and content data.

At the moment, I'll update

```
@Parcelize
data class SurveyUiModel(
    val id: String,
    val title: String?,
    val description: String?,
    val coverImageUrl: String?
) : Parcelable {

    fun getUrlHighResolution(): String = ModelUtil.mapToUrlHighResolution(coverImageUrl)
}
```

If there is anything that needs to be updated, please let me know. :)

**Comment by longdt57** [comment]
Fixed in PR #39

**Comment by hoangnguyen92dn** [comment]
> If we never use the origin coverImageUrl, I suggest replacing it with coverImageHighResolutionUrl at all to reduce the duplicate variable and content data.

That's fine. If we don't use any property we could clean it. But the key here is all the properties from UiModel should not be modified outside of scope.

**Comment by longdt57** [comment]
I got your idea. I'll update it soon
