### ISSUE TITLE
[Improvement] Add UnitTest to increase code coverage on ViewModel

### ISSUE THREAD

**Issue by hoangnguyen92dn** [longdt57/nimble-android-assignment#29]
### Issue

It's good to have UnitTest for UseCase on your first submission, for a better code coverage report, would it be possible to add more UnitTest on the ViewModel layer? 

### Expected

Adding more UnitTest to cover ViewModel classes

**Comment by longdt57** [comment]
I've started adding ViewModel Test in PR #40

**Comment by longdt57** [comment]
I added ViewModel Test in PR #40 and #42
