### ISSUE TITLE
[Improvement] Adding Instrumented Test for UI

### ISSUE THREAD

**Issue by hoangnguyen92dn** [longdt57/nimble-android-assignment#30]
## Issue

As you already mentioned in the email, there is no Instrumented test case for the UI part to test the behavior of user actions.

## Expected

I would suggest adding some Instrumented Tests for screens to verify the app behavior on user actions.

**Comment by longdt57** [comment]
Start adding test in #4

**Comment by longdt57** [comment]
Added SignInFragment Instrument Test.

**Comment by hoangnguyen92dn** [comment]
@longdt57 Thank you. I will finalize review and evaluate with our team for the final result. Our TA will reach you once completed.

**Comment by longdt57** [comment]
Thank you @hoangnguyen92dn,

I look forward to hearing from your team soon.

**Comment by longdt57** [comment]
PR #44 was merged
