### ISSUE TITLE
[Question] Default page size and page number in the SurveyMetaResponse

### ISSUE THREAD

**Issue by hoangnguyen92dn** [longdt57/nimble-android-assignment#31]
### Issue

I am curious why you are setting default `page_size` and `page_number` in the `SurveyMetaResponse`, normally the `page_size` and `page_number` are added in the API request from the higher layer instead. 🤔 

https://github.com/longdt57/nimble-android-assignment/blob/0249943d406b6975f9bf93cab1ef88686d4a0ca1/data/src/main/java/co/nimble/lee/assignment/data/response/SurveyMetaResponse.kt#L7-L27

**Comment by longdt57** [comment]
I set this from the request **GETSurvey list**
```
page[number]
1
Default: 1

page[size]
2
Default: 5
```

Removed in MR #34

**Comment by hoangnguyen92dn** [comment]
@longdt57 Btw, just a suggestion that you created the constant in the Response class and then used a magic number in the UseCase, tt should refer to the same constant to avoid confusion.

https://github.com/longdt57/nimble-android-assignment/blob/e0533f42b9d26462b83468a2d13987b706ba3276/domain/src/main/java/co/nimble/lee/assignment/domain/usecase/GetSurveyUseCase.kt#L30-L33
